### ISSUE TITLE
Scope with gulp-postcss

### ISSUE THREAD

**Issue by Aetet** [pazams/postcss-scopify#1]
Hello. I have a question about usage postcss plugins with gulp usage. Let's say I have https://github.com/pazams/postcss-scopify . And each time I process file I want to take his name as scope. How I can achieve that? Does postcss plugins has access to gulp primitives at build phase?

**Comment by pazams** [comment]
Hi @Aetet, I think your question better belongs to gulp-postcss (https://github.com/postcss/gulp-postcss). I'd also look into the suggestions mentioned here: http://stackoverflow.com/questions/21806925/get-the-current-file-name-in-gulp-src
