### ISSUE TITLE
Not scopifying @media, @container..

### ISSUE THREAD

**Issue by akbar-idwise** [pazams/postcss-scopify#18]
The plugin is not scopifying anything that not a class identifier or id identifier:

These valid css won't get scopified.
```
@media (min-width: 640px) {
}
```
```
@container (min-width:24rem) {
    .\@sm\:\!max-w-lg {
        max-width: 32rem !important
    }
}
```

specially the `@container` which is scope specific. Please see: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries

**Comment by pazams** [comment]
There is special logic for "at rules" by design.
See the at-rule testing fixtures here:
- before scope https://github.com/pazams/postcss-scopify/blob/master/test/fixtures/at-rules.css
- after scope https://github.com/pazams/postcss-scopify/blob/master/test/fixtures/at-rules.expected.css
